// Auto-generated RV32I Full Coverage Test
// DO NOT EDIT - Generated by isa_full_coverage_gen.py

.text
.globl _start

_start:
// Initialize test registers with known values
    addi x1, x0, 1
    addi x2, x0, 2
    addi x3, x0, 3
    addi x4, x0, 4
    addi x5, x0, 8

// === R-Type ALU Instructions ===

    add x10, x1, x2
    sw x10, 0(x0)  // Expect: 3 (ADD)
    sub x11, x3, x1
    sw x11, 4(x0)  // Expect: 2 (SUB)
    and x12, x2, x3
    sw x12, 8(x0)  // Expect: 2 (AND)
    or x13, x1, x2
    sw x13, 12(x0)  // Expect: 3 (OR)
    xor x14, x2, x3
    sw x14, 16(x0)  // Expect: 1 (XOR)
    sll x15, x2, x1
    sw x15, 20(x0)  // Expect: 4 (SLL)
    srl x16, x5, x1
    sw x16, 24(x0)  // Expect: 4 (SRL)
    sra x17, x5, x1
    sw x17, 28(x0)  // Expect: 4 (SRA)
    slt x18, x1, x2
    sw x18, 32(x0)  // Expect: 1 (SLT)
    sltu x19, x1, x2
    sw x19, 36(x0)  // Expect: 1 (SLTU)

// === I-Type ALU Instructions ===

    addi x20, x1, 10
    sw x20, 40(x0)  // Expect: 11 (ADDI)
    slti x21, x1, 2
    sw x21, 44(x0)  // Expect: 1 (SLTI)
    sltiu x22, x1, 2
    sw x22, 48(x0)  // Expect: 1 (SLTIU)
    xori x23, x2, 3
    sw x23, 52(x0)  // Expect: 1 (XORI)
    ori x24, x1, 2
    sw x24, 56(x0)  // Expect: 3 (ORI)
    andi x25, x3, 2
    sw x25, 60(x0)  // Expect: 2 (ANDI)
    slli x26, x2, 2
    sw x26, 64(x0)  // Expect: 8 (SLLI)
    srli x27, x5, 1
    sw x27, 68(x0)  // Expect: 4 (SRLI)
    srai x28, x5, 1
    sw x28, 72(x0)  // Expect: 4 (SRAI)

// === Upper Immediate Instructions ===

    lui x6, 0x12345
    sw x6, 76(x0)  // Expect: 305418240 (LUI)
    auipc x7, 0
    sw x7, 80(x0)  // Expect: 4294967295 (AUIPC - unpredictable)

// === Load/Store Instructions ===

    addi x8, x0, 0xAB
    addi x9, x0, 200
    sw x8, 0(x9)
    lw x10, 0(x9)
    sw x10, 84(x0)  // Expect: 171 (LW)
    addi x11, x0, 0xCD
    sh x11, 4(x9)
    lh x12, 4(x9)
    sw x12, 88(x0)  // Expect: 205 (LH)
    lhu x13, 4(x9)
    sw x13, 92(x0)  // Expect: 205 (LHU)
    addi x14, x0, 0x42
    sb x14, 8(x9)
    lb x15, 8(x9)
    sw x15, 96(x0)  // Expect: 66 (LB)
    lbu x16, 8(x9)
    sw x16, 100(x0)  // Expect: 66 (LBU)

// === Branch Instructions ===

    beq x1, x1, beq_taken
    addi x17, x0, 999  // Should skip
    j test_fail
beq_taken:
    addi x17, x0, 1
    sw x17, 104(x0)  // Expect: 1 (BEQ)
    bne x1, x2, bne_taken
    j test_fail
bne_taken:
    addi x18, x0, 2
    sw x18, 108(x0)  // Expect: 2 (BNE)
    blt x1, x2, blt_taken
    j test_fail
blt_taken:
    addi x19, x0, 3
    sw x19, 112(x0)  // Expect: 3 (BLT)
    bge x2, x1, bge_taken
    j test_fail
bge_taken:
    addi x20, x0, 4
    sw x20, 116(x0)  // Expect: 4 (BGE)
    bltu x1, x2, bltu_taken
    j test_fail
bltu_taken:
    addi x21, x0, 5
    sw x21, 120(x0)  // Expect: 5 (BLTU)
    bgeu x2, x1, bgeu_taken
    j test_fail
bgeu_taken:
    addi x22, x0, 6
    sw x22, 124(x0)  // Expect: 6 (BGEU)

// === Jump Instructions ===

    jal x23, jal_target
    j test_fail
jal_target:
    sw x23, 128(x0)  // Expect: 4294967295 (JAL return addr - unpredictable)
    lui x24, %hi(jalr_target)
    addi x24, x24, %lo(jalr_target)
    jalr x25, 0(x24)
    j test_fail
jalr_target:
    sw x25, 132(x0)  // Expect: 4294967295 (JALR return addr - unpredictable)

// === Signature Verification ===

    addi x31, x0, 0  // Accumulator
    lw x30, 0(x0)
    add x31, x31, x30
    lw x30, 4(x0)
    add x31, x31, x30
    lw x30, 8(x0)
    add x31, x31, x30
    lw x30, 12(x0)
    add x31, x31, x30
    lw x30, 16(x0)
    add x31, x31, x30
    lw x30, 20(x0)
    add x31, x31, x30
    lw x30, 24(x0)
    add x31, x31, x30
    lw x30, 28(x0)
    add x31, x31, x30
    lw x30, 32(x0)
    add x31, x31, x30
    lw x30, 36(x0)
    add x31, x31, x30
    lw x30, 40(x0)
    add x31, x31, x30
    lw x30, 44(x0)
    add x31, x31, x30
    lw x30, 48(x0)
    add x31, x31, x30
    lw x30, 52(x0)
    add x31, x31, x30
    lw x30, 56(x0)
    add x31, x31, x30
    lw x30, 60(x0)
    add x31, x31, x30
    lw x30, 64(x0)
    add x31, x31, x30
    lw x30, 68(x0)
    add x31, x31, x30
    lw x30, 72(x0)
    add x31, x31, x30
    lw x30, 76(x0)
    add x31, x31, x30
    lw x30, 84(x0)
    add x31, x31, x30
    lw x30, 88(x0)
    add x31, x31, x30
    lw x30, 92(x0)
    add x31, x31, x30
    lw x30, 96(x0)
    add x31, x31, x30
    lw x30, 100(x0)
    add x31, x31, x30
    lw x30, 104(x0)
    add x31, x31, x30
    lw x30, 108(x0)
    add x31, x31, x30
    lw x30, 112(x0)
    add x31, x31, x30
    lw x30, 116(x0)
    add x31, x31, x30
    lw x30, 120(x0)
    add x31, x31, x30
    lw x30, 124(x0)
    add x31, x31, x30

// Expected checksum: 0x1234531a
    lui x29, 74565
    addi x29, x29, 794
    beq x31, x29, test_pass

test_fail:
    ebreak

test_pass:
    addi x1, x0, 0xC0DE  // Success marker
    ebreak

// ===== COVERAGE REPORT =====
// Coverage: 38/38 instructions (100.0%)
//
// ALU_R:
//   ✓ ADD
//   ✓ SUB
//   ✓ SLL
//   ✓ SLT
//   ✓ SLTU
//   ✓ XOR
//   ✓ SRL
//   ✓ SRA
//   ✓ OR
//   ✓ AND
// ALU_I:
//   ✓ ADDI
//   ✓ SLTI
//   ✓ SLTIU
//   ✓ XORI
//   ✓ ORI
//   ✓ ANDI
//   ✓ SLLI
//   ✓ SRLI
//   ✓ SRAI
// LOAD:
//   ✓ LB
//   ✓ LH
//   ✓ LW
//   ✓ LBU
//   ✓ LHU
// STORE:
//   ✓ SB
//   ✓ SH
//   ✓ SW
// BRANCH:
//   ✓ BEQ
//   ✓ BNE
//   ✓ BLT
//   ✓ BGE
//   ✓ BLTU
//   ✓ BGEU
// JUMP:
//   ✓ JAL
//   ✓ JALR
// UPPER:
//   ✓ LUI
//   ✓ AUIPC
// SYSTEM:
//   ✓ EBREAK
// ===========================